import type { SystemRepository } from '../data/repositories/systemRepository'
import { createSystemRoadmapService } from './systemRoadmaps'
import { createDailyDirective, createDirectiveObjective, deriveDirectiveCandidates, localDateKey, type DirectiveCandidate, type SystemDailyDirective, type SystemDirectiveObjective } from '../domain/systemDailyDirective'
import type { SystemData } from '../domain/systemPathGoal'

export type DirectiveOperationResult = { readonly ok: true; readonly data: SystemData } | { readonly ok: false; readonly problem: string; readonly message: string }
const messages: Record<string, string> = { 'storage-unavailable': 'System storage is unavailable. Your saved data is untouched.', 'quota-exceeded': 'Storage is full. Your saved data is untouched.', 'newer-schema': 'This System needs a newer ASCEND version. Saved data is untouched.', 'invalid-data': 'System data could not be read safely. Saved data is untouched.', 'not-found': 'That record is no longer available.', 'invalid-input': 'Review the directive details and try again.' }
const fail = (problem: string): DirectiveOperationResult => ({ ok: false, problem, message: messages[problem] ?? messages['invalid-input']! })
const write = (repository: SystemRepository, data: SystemData): DirectiveOperationResult => { const result = repository.save(data); return result === 'ok' ? { ok: true, data } : fail(result === 'unavailable' ? 'storage-unavailable' : result) }
const load = (repository: SystemRepository): { ok: true; data: SystemData } | { ok: false; problem: string } => { const result = repository.read(); return result.ok ? { ok: true, data: result.value ?? { schemaVersion: 3, paths: [], goals: [], roadmaps: [], roadmapPhases: [], roadmapSteps: [], directives: [], directiveObjectives: [] } } : { ok: false, problem: result.problem } }

export interface SystemDirectiveService {
  current(dateKey?: string): { directive: SystemDailyDirective | null; objectives: SystemDirectiveObjective[] }
  candidates(): DirectiveCandidate[]
  accept(candidate: DirectiveCandidate, input: { dateKey?: string; title?: string; description?: string; why?: string; now: string }): DirectiveOperationResult
  manual(input: { dateKey?: string; title: string; description?: string; why?: string; now: string }): DirectiveOperationResult
  edit(id: string, input: { title: string; description?: string; why?: string; now: string }): DirectiveOperationResult
  replace(id: string, input: { candidate?: DirectiveCandidate; title?: string; description?: string; why?: string; dateKey?: string; now: string }): DirectiveOperationResult
  abandon(id: string, now: string): DirectiveOperationResult
  complete(id: string, now: string): DirectiveOperationResult
  objectiveAdd(directiveId: string, title: string, now: string): DirectiveOperationResult
  objectiveEdit(id: string, title: string, now: string): DirectiveOperationResult
  objectiveToggle(id: string, now: string): DirectiveOperationResult
  objectiveReorder(directiveId: string, ids: readonly string[], now: string): DirectiveOperationResult
  objectiveRemove(id: string, now: string): DirectiveOperationResult
  completeLinkedRoadmapStep(directiveId: string, now: string): DirectiveOperationResult
}

export function createSystemDirectiveService(repository: SystemRepository): SystemDirectiveService {
  const roadmapService = createSystemRoadmapService(repository)
  const current = (dateKey = localDateKey()) => { const loaded = load(repository); if (!loaded.ok) return { directive: null, objectives: [] }; const directive = [...loaded.data.directives].reverse().find(entry => entry.dateKey === dateKey && entry.status === 'ACTIVE') ?? [...loaded.data.directives].reverse().find(entry => entry.dateKey === dateKey && entry.status === 'COMPLETED') ?? null; return { directive, objectives: directive ? loaded.data.directiveObjectives.filter(entry => entry.directiveId === directive.id).sort((a, b) => a.order - b.order) : [] } }
  const mutate = (fn: (data: SystemData) => SystemData): DirectiveOperationResult => { const loaded = load(repository); if (!loaded.ok) return fail(loaded.problem); try { return write(repository, fn(loaded.data)) } catch (error) { return error instanceof Error ? fail('invalid-input') : fail('invalid-input') } }
  const activeToday = (data: SystemData, dateKey: string) => data.directives.find(entry => entry.dateKey === dateKey && entry.status === 'ACTIVE')
  return {
    current,
    candidates: () => { const loaded = load(repository); return loaded.ok ? deriveDirectiveCandidates(loaded.data) : [] },
    accept(candidate, input) { const dateKey = input.dateKey ?? localDateKey(); return mutate(data => { if (activeToday(data, dateKey)) throw new Error('A directive is already active'); const directive = createDailyDirective({ dateKey, title: input.title ?? candidate.step.title, description: input.description, why: input.why ?? candidate.goal.why, sourceType: 'ROADMAP_STEP', sourceRoadmapStepId: candidate.step.id, now: input.now }); const objective = createDirectiveObjective({ directiveId: directive.id, title: candidate.step.title, order: 0, now: input.now }); return { ...data, directives: [...data.directives, directive], directiveObjectives: [...data.directiveObjectives, objective] } }) },
    manual(input) { const dateKey = input.dateKey ?? localDateKey(); return mutate(data => { if (activeToday(data, dateKey)) throw new Error('A directive is already active'); const directive = createDailyDirective({ ...input, dateKey, sourceType: 'MANUAL' }); const objective = createDirectiveObjective({ directiveId: directive.id, title: directive.title, order: 0, now: input.now }); return { ...data, directives: [...data.directives, directive], directiveObjectives: [...data.directiveObjectives, objective] } }) },
    edit(id, input) { return mutate(data => { const found = data.directives.find(entry => entry.id === id); if (!found) throw new Error('Not found'); const updated = createDailyDirective({ ...found, ...input, id: found.id, sourceType: found.sourceType, dateKey: found.dateKey, now: input.now }); return { ...data, directives: data.directives.map(entry => entry.id === id ? { ...found, ...updated, status: found.status as SystemDailyDirective['status'], completedAt: found.completedAt, createdAt: found.createdAt } : entry) } }) },
    replace(id, input) { return mutate(data => { const found = data.directives.find(entry => entry.id === id); if (!found || found.status !== 'ACTIVE') throw new Error('Not found'); const dateKey = input.dateKey ?? found.dateKey; const candidate = input.candidate; const next = candidate ? createDailyDirective({ dateKey, title: input.title ?? candidate.step.title, description: input.description, why: input.why ?? candidate.goal.why, sourceType: 'ROADMAP_STEP', sourceRoadmapStepId: candidate.step.id, now: input.now }) : createDailyDirective({ dateKey, title: input.title ?? found.title, description: input.description, why: input.why, sourceType: 'MANUAL', now: input.now }); const objective = createDirectiveObjective({ directiveId: next.id, title: candidate?.step.title ?? next.title, order: 0, now: input.now }); return { ...data, directives: data.directives.map(entry => entry.id === id ? { ...entry, status: 'ABANDONED' as const, updatedAt: input.now } : entry).concat(next), directiveObjectives: [...data.directiveObjectives, objective] } }) },
    abandon(id, now) { return mutate(data => { const found = data.directives.find(entry => entry.id === id); if (!found) throw new Error('Not found'); return { ...data, directives: data.directives.map(entry => entry.id === id ? { ...entry, status: 'ABANDONED' as const, updatedAt: now } : entry) } }) },
    complete(id, now) { return mutate(data => { const found = data.directives.find(entry => entry.id === id); if (!found || found.status !== 'ACTIVE') throw new Error('Not found'); const objectives = data.directiveObjectives.filter(entry => entry.directiveId === id); if (objectives.some(entry => !entry.completedAt)) throw new Error('Complete all objectives first'); return { ...data, directives: data.directives.map(entry => entry.id === id ? { ...entry, status: 'COMPLETED' as const, completedAt: now, updatedAt: now } : entry) } }) },
    objectiveAdd(directiveId, title, now) { return mutate(data => { const directive = data.directives.find(entry => entry.id === directiveId && entry.status === 'ACTIVE'); if (!directive) throw new Error('Not found'); const order = data.directiveObjectives.filter(entry => entry.directiveId === directiveId).length; const objective = createDirectiveObjective({ directiveId, title, order, now }); return { ...data, directiveObjectives: [...data.directiveObjectives, objective] } }) },
    objectiveEdit(id, title, now) { return mutate(data => { if (!data.directiveObjectives.some(entry => entry.id === id)) throw new Error('Not found'); return { ...data, directiveObjectives: data.directiveObjectives.map(entry => entry.id === id ? { ...entry, title: title.trim(), updatedAt: now } : entry) } }) },
    objectiveToggle(id, now) { return mutate(data => { if (!data.directiveObjectives.some(entry => entry.id === id)) throw new Error('Not found'); return { ...data, directiveObjectives: data.directiveObjectives.map(entry => entry.id === id ? { ...entry, completedAt: entry.completedAt ? null : now, updatedAt: now } : entry) } }) },
    objectiveReorder(directiveId, ids, now) { return mutate(data => { const entries = data.directiveObjectives.filter(entry => entry.directiveId === directiveId); if (entries.length !== ids.length || new Set(ids).size !== ids.length || entries.some(entry => !ids.includes(entry.id))) throw new Error('Invalid order'); return { ...data, directiveObjectives: data.directiveObjectives.map(entry => entry.directiveId === directiveId ? { ...entry, order: ids.indexOf(entry.id), updatedAt: now } : entry) } }) },
    objectiveRemove(id, now) { return mutate(data => { const found = data.directiveObjectives.find(entry => entry.id === id); if (!found) throw new Error('Not found'); const remaining = data.directiveObjectives.filter(entry => entry.id !== id && entry.directiveId === found.directiveId).sort((a, b) => a.order - b.order).map((entry, order) => ({ ...entry, order, updatedAt: now })); return { ...data, directiveObjectives: [...data.directiveObjectives.filter(entry => entry.directiveId !== found.directiveId), ...remaining] } }) },
    completeLinkedRoadmapStep(directiveId, now) { const loaded = load(repository); if (!loaded.ok) return fail(loaded.problem); const directive = loaded.data.directives.find(entry => entry.id === directiveId); if (!directive?.sourceRoadmapStepId) return fail('not-found'); const result = roadmapService.complete(directive.sourceRoadmapStepId, now); return result.ok ? result : fail(result.problem) },
  }
}
